// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	node_service.proto

It has these top-level messages:
	Empty
	StateResponse
	ModifyResponse
	BaseResponse
	NodeState
	ServiceDescription
	NodeDescription
	PortDescription
	LinkRequest
	UpdateRequest
	GetStateRequest
	CreateRequest
	Identifiers
	PortIdentifier
	NodeIdentifier
	RequestData
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LinkType int32

const (
	LinkType_SIMPLE      LinkType = 0
	LinkType_WEAK_FIRST  LinkType = 1
	LinkType_WEAK_SECOND LinkType = 2
	LinkType_WEAK_BOTH   LinkType = 3
)

var LinkType_name = map[int32]string{
	0: "SIMPLE",
	1: "WEAK_FIRST",
	2: "WEAK_SECOND",
	3: "WEAK_BOTH",
}
var LinkType_value = map[string]int32{
	"SIMPLE":      0,
	"WEAK_FIRST":  1,
	"WEAK_SECOND": 2,
	"WEAK_BOTH":   3,
}

func (x LinkType) String() string {
	return proto.EnumName(LinkType_name, int32(x))
}
func (LinkType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeDescription_AttachedPortDescription_PortType int32

const (
	NodeDescription_AttachedPortDescription_INPUT             NodeDescription_AttachedPortDescription_PortType = 0
	NodeDescription_AttachedPortDescription_OUTPUT            NodeDescription_AttachedPortDescription_PortType = 1
	NodeDescription_AttachedPortDescription_NEUTRAL           NodeDescription_AttachedPortDescription_PortType = 2
	NodeDescription_AttachedPortDescription_CONTEXT_DEPENDENT NodeDescription_AttachedPortDescription_PortType = 3
)

var NodeDescription_AttachedPortDescription_PortType_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
	2: "NEUTRAL",
	3: "CONTEXT_DEPENDENT",
}
var NodeDescription_AttachedPortDescription_PortType_value = map[string]int32{
	"INPUT":             0,
	"OUTPUT":            1,
	"NEUTRAL":           2,
	"CONTEXT_DEPENDENT": 3,
}

func (x NodeDescription_AttachedPortDescription_PortType) String() string {
	return proto.EnumName(NodeDescription_AttachedPortDescription_PortType_name, int32(x))
}
func (NodeDescription_AttachedPortDescription_PortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1, 0}
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StateResponse struct {
	Base  *BaseResponse                 `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Items []*StateResponse_UnitResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StateResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *StateResponse) GetItems() []*StateResponse_UnitResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type StateResponse_UnitResponse struct {
	Base       *BaseResponse   `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Identifier *NodeIdentifier `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	State      *NodeState      `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
}

func (m *StateResponse_UnitResponse) Reset()                    { *m = StateResponse_UnitResponse{} }
func (m *StateResponse_UnitResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse_UnitResponse) ProtoMessage()               {}
func (*StateResponse_UnitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *StateResponse_UnitResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *StateResponse_UnitResponse) GetIdentifier() *NodeIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *StateResponse_UnitResponse) GetState() *NodeState {
	if m != nil {
		return m.State
	}
	return nil
}

type ModifyResponse struct {
	Base  *BaseResponse                  `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Items []*ModifyResponse_UnitResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *ModifyResponse) Reset()                    { *m = ModifyResponse{} }
func (m *ModifyResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyResponse) ProtoMessage()               {}
func (*ModifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModifyResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ModifyResponse) GetItems() []*ModifyResponse_UnitResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type ModifyResponse_UnitResponse struct {
	Identifiers []*NodeIdentifier `protobuf:"bytes,1,rep,name=identifiers" json:"identifiers,omitempty"`
	Base        *BaseResponse     `protobuf:"bytes,2,opt,name=base" json:"base,omitempty"`
}

func (m *ModifyResponse_UnitResponse) Reset()                    { *m = ModifyResponse_UnitResponse{} }
func (m *ModifyResponse_UnitResponse) String() string            { return proto.CompactTextString(m) }
func (*ModifyResponse_UnitResponse) ProtoMessage()               {}
func (*ModifyResponse_UnitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *ModifyResponse_UnitResponse) GetIdentifiers() []*NodeIdentifier {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *ModifyResponse_UnitResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type BaseResponse struct {
	Status      int32  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *BaseResponse) Reset()                    { *m = BaseResponse{} }
func (m *BaseResponse) String() string            { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()               {}
func (*BaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BaseResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BaseResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type NodeState struct {
	Name         string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NumValues    map[string]float64    `protobuf:"bytes,2,rep,name=numValues" json:"numValues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringValues map[string]string     `protobuf:"bytes,3,rep,name=stringValues" json:"stringValues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Children     map[string]*NodeState `protobuf:"bytes,4,rep,name=children" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *NodeState) Reset()                    { *m = NodeState{} }
func (m *NodeState) String() string            { return proto.CompactTextString(m) }
func (*NodeState) ProtoMessage()               {}
func (*NodeState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NodeState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeState) GetNumValues() map[string]float64 {
	if m != nil {
		return m.NumValues
	}
	return nil
}

func (m *NodeState) GetStringValues() map[string]string {
	if m != nil {
		return m.StringValues
	}
	return nil
}

func (m *NodeState) GetChildren() map[string]*NodeState {
	if m != nil {
		return m.Children
	}
	return nil
}

type ServiceDescription struct {
	Description string             `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Nodes       []*NodeDescription `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ServiceDescription) Reset()                    { *m = ServiceDescription{} }
func (m *ServiceDescription) String() string            { return proto.CompactTextString(m) }
func (*ServiceDescription) ProtoMessage()               {}
func (*ServiceDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ServiceDescription) GetNodes() []*NodeDescription {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeDescription struct {
	NodeType      string                                     `protobuf:"bytes,1,opt,name=NodeType" json:"NodeType,omitempty"`
	BasePorts     []*NodeDescription_AttachedPortDescription `protobuf:"bytes,2,rep,name=basePorts" json:"basePorts,omitempty"`
	ContextStates []*NodeDescription_ContextState            `protobuf:"bytes,3,rep,name=contextStates" json:"contextStates,omitempty"`
}

func (m *NodeDescription) Reset()                    { *m = NodeDescription{} }
func (m *NodeDescription) String() string            { return proto.CompactTextString(m) }
func (*NodeDescription) ProtoMessage()               {}
func (*NodeDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeDescription) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *NodeDescription) GetBasePorts() []*NodeDescription_AttachedPortDescription {
	if m != nil {
		return m.BasePorts
	}
	return nil
}

func (m *NodeDescription) GetContextStates() []*NodeDescription_ContextState {
	if m != nil {
		return m.ContextStates
	}
	return nil
}

type NodeDescription_ContextState struct {
	Ports []*NodeDescription_AttachedPortDescription `protobuf:"bytes,1,rep,name=ports" json:"ports,omitempty"`
}

func (m *NodeDescription_ContextState) Reset()                    { *m = NodeDescription_ContextState{} }
func (m *NodeDescription_ContextState) String() string            { return proto.CompactTextString(m) }
func (*NodeDescription_ContextState) ProtoMessage()               {}
func (*NodeDescription_ContextState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *NodeDescription_ContextState) GetPorts() []*NodeDescription_AttachedPortDescription {
	if m != nil {
		return m.Ports
	}
	return nil
}

type NodeDescription_AttachedPortDescription struct {
	Description *PortDescription                                 `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        NodeDescription_AttachedPortDescription_PortType `protobuf:"varint,2,opt,name=type,enum=nodeservice.NodeDescription_AttachedPortDescription_PortType" json:"type,omitempty"`
}

func (m *NodeDescription_AttachedPortDescription) Reset() {
	*m = NodeDescription_AttachedPortDescription{}
}
func (m *NodeDescription_AttachedPortDescription) String() string { return proto.CompactTextString(m) }
func (*NodeDescription_AttachedPortDescription) ProtoMessage()    {}
func (*NodeDescription_AttachedPortDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1}
}

func (m *NodeDescription_AttachedPortDescription) GetDescription() *PortDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *NodeDescription_AttachedPortDescription) GetType() NodeDescription_AttachedPortDescription_PortType {
	if m != nil {
		return m.Type
	}
	return NodeDescription_AttachedPortDescription_INPUT
}

type PortDescription struct {
	Prefix  string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	IsMulti bool   `protobuf:"varint,2,opt,name=isMulti" json:"isMulti,omitempty"`
}

func (m *PortDescription) Reset()                    { *m = PortDescription{} }
func (m *PortDescription) String() string            { return proto.CompactTextString(m) }
func (*PortDescription) ProtoMessage()               {}
func (*PortDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PortDescription) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *PortDescription) GetIsMulti() bool {
	if m != nil {
		return m.IsMulti
	}
	return false
}

type LinkRequest struct {
	Items []*LinkRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *LinkRequest) Reset()                    { *m = LinkRequest{} }
func (m *LinkRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()               {}
func (*LinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *LinkRequest) GetItems() []*LinkRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type LinkRequest_UnitRequest struct {
	LinkType LinkType        `protobuf:"varint,1,opt,name=linkType,enum=nodeservice.LinkType" json:"linkType,omitempty"`
	Id1      *PortIdentifier `protobuf:"bytes,2,opt,name=id1" json:"id1,omitempty"`
	Id2      *PortIdentifier `protobuf:"bytes,3,opt,name=id2" json:"id2,omitempty"`
}

func (m *LinkRequest_UnitRequest) Reset()                    { *m = LinkRequest_UnitRequest{} }
func (m *LinkRequest_UnitRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest_UnitRequest) ProtoMessage()               {}
func (*LinkRequest_UnitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *LinkRequest_UnitRequest) GetLinkType() LinkType {
	if m != nil {
		return m.LinkType
	}
	return LinkType_SIMPLE
}

func (m *LinkRequest_UnitRequest) GetId1() *PortIdentifier {
	if m != nil {
		return m.Id1
	}
	return nil
}

func (m *LinkRequest_UnitRequest) GetId2() *PortIdentifier {
	if m != nil {
		return m.Id2
	}
	return nil
}

type UpdateRequest struct {
	Items []*UpdateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateRequest) GetItems() []*UpdateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type UpdateRequest_UnitRequest struct {
	Identifier *NodeIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Data       *RequestData    `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *UpdateRequest_UnitRequest) Reset()                    { *m = UpdateRequest_UnitRequest{} }
func (m *UpdateRequest_UnitRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest_UnitRequest) ProtoMessage()               {}
func (*UpdateRequest_UnitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *UpdateRequest_UnitRequest) GetIdentifier() *NodeIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *UpdateRequest_UnitRequest) GetData() *RequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetStateRequest struct {
	Items []*GetStateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *GetStateRequest) Reset()                    { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()               {}
func (*GetStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetStateRequest) GetItems() []*GetStateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetStateRequest_UnitRequest struct {
	Identifier *NodeIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// optional field neccessary if complete state is not required
	RequiredFields []string `protobuf:"bytes,2,rep,name=requiredFields" json:"requiredFields,omitempty"`
}

func (m *GetStateRequest_UnitRequest) Reset()                    { *m = GetStateRequest_UnitRequest{} }
func (m *GetStateRequest_UnitRequest) String() string            { return proto.CompactTextString(m) }
func (*GetStateRequest_UnitRequest) ProtoMessage()               {}
func (*GetStateRequest_UnitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

func (m *GetStateRequest_UnitRequest) GetIdentifier() *NodeIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *GetStateRequest_UnitRequest) GetRequiredFields() []string {
	if m != nil {
		return m.RequiredFields
	}
	return nil
}

type CreateRequest struct {
	Items []*CreateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateRequest) GetItems() []*CreateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateRequest_UnitRequest struct {
	NodeName string       `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	NodeType string       `protobuf:"bytes,2,opt,name=nodeType" json:"nodeType,omitempty"`
	Data     *RequestData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *CreateRequest_UnitRequest) Reset()                    { *m = CreateRequest_UnitRequest{} }
func (m *CreateRequest_UnitRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest_UnitRequest) ProtoMessage()               {}
func (*CreateRequest_UnitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

func (m *CreateRequest_UnitRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *CreateRequest_UnitRequest) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *CreateRequest_UnitRequest) GetData() *RequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Identifiers struct {
	Ids []*NodeIdentifier `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *Identifiers) Reset()                    { *m = Identifiers{} }
func (m *Identifiers) String() string            { return proto.CompactTextString(m) }
func (*Identifiers) ProtoMessage()               {}
func (*Identifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Identifiers) GetIds() []*NodeIdentifier {
	if m != nil {
		return m.Ids
	}
	return nil
}

type PortIdentifier struct {
	NodeIdentifier *NodeIdentifier `protobuf:"bytes,1,opt,name=nodeIdentifier" json:"nodeIdentifier,omitempty"`
	PortTag        string          `protobuf:"bytes,2,opt,name=portTag" json:"portTag,omitempty"`
}

func (m *PortIdentifier) Reset()                    { *m = PortIdentifier{} }
func (m *PortIdentifier) String() string            { return proto.CompactTextString(m) }
func (*PortIdentifier) ProtoMessage()               {}
func (*PortIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PortIdentifier) GetNodeIdentifier() *NodeIdentifier {
	if m != nil {
		return m.NodeIdentifier
	}
	return nil
}

func (m *PortIdentifier) GetPortTag() string {
	if m != nil {
		return m.PortTag
	}
	return ""
}

type NodeIdentifier struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	NodeType string `protobuf:"bytes,2,opt,name=nodeType" json:"nodeType,omitempty"`
}

func (m *NodeIdentifier) Reset()                    { *m = NodeIdentifier{} }
func (m *NodeIdentifier) String() string            { return proto.CompactTextString(m) }
func (*NodeIdentifier) ProtoMessage()               {}
func (*NodeIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *NodeIdentifier) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeIdentifier) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

type RequestData struct {
	DArgs   []float64          `protobuf:"fixed64,1,rep,packed,name=dArgs" json:"dArgs,omitempty"`
	SArgs   []string           `protobuf:"bytes,2,rep,name=sArgs" json:"sArgs,omitempty"`
	DKwargs map[string]float64 `protobuf:"bytes,3,rep,name=dKwargs" json:"dKwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SKwargs map[string]string  `protobuf:"bytes,4,rep,name=sKwargs" json:"sKwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RequestData) Reset()                    { *m = RequestData{} }
func (m *RequestData) String() string            { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()               {}
func (*RequestData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RequestData) GetDArgs() []float64 {
	if m != nil {
		return m.DArgs
	}
	return nil
}

func (m *RequestData) GetSArgs() []string {
	if m != nil {
		return m.SArgs
	}
	return nil
}

func (m *RequestData) GetDKwargs() map[string]float64 {
	if m != nil {
		return m.DKwargs
	}
	return nil
}

func (m *RequestData) GetSKwargs() map[string]string {
	if m != nil {
		return m.SKwargs
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "nodeservice.Empty")
	proto.RegisterType((*StateResponse)(nil), "nodeservice.StateResponse")
	proto.RegisterType((*StateResponse_UnitResponse)(nil), "nodeservice.StateResponse.UnitResponse")
	proto.RegisterType((*ModifyResponse)(nil), "nodeservice.ModifyResponse")
	proto.RegisterType((*ModifyResponse_UnitResponse)(nil), "nodeservice.ModifyResponse.UnitResponse")
	proto.RegisterType((*BaseResponse)(nil), "nodeservice.BaseResponse")
	proto.RegisterType((*NodeState)(nil), "nodeservice.NodeState")
	proto.RegisterType((*ServiceDescription)(nil), "nodeservice.ServiceDescription")
	proto.RegisterType((*NodeDescription)(nil), "nodeservice.NodeDescription")
	proto.RegisterType((*NodeDescription_ContextState)(nil), "nodeservice.NodeDescription.ContextState")
	proto.RegisterType((*NodeDescription_AttachedPortDescription)(nil), "nodeservice.NodeDescription.AttachedPortDescription")
	proto.RegisterType((*PortDescription)(nil), "nodeservice.PortDescription")
	proto.RegisterType((*LinkRequest)(nil), "nodeservice.LinkRequest")
	proto.RegisterType((*LinkRequest_UnitRequest)(nil), "nodeservice.LinkRequest.UnitRequest")
	proto.RegisterType((*UpdateRequest)(nil), "nodeservice.UpdateRequest")
	proto.RegisterType((*UpdateRequest_UnitRequest)(nil), "nodeservice.UpdateRequest.UnitRequest")
	proto.RegisterType((*GetStateRequest)(nil), "nodeservice.GetStateRequest")
	proto.RegisterType((*GetStateRequest_UnitRequest)(nil), "nodeservice.GetStateRequest.UnitRequest")
	proto.RegisterType((*CreateRequest)(nil), "nodeservice.CreateRequest")
	proto.RegisterType((*CreateRequest_UnitRequest)(nil), "nodeservice.CreateRequest.UnitRequest")
	proto.RegisterType((*Identifiers)(nil), "nodeservice.Identifiers")
	proto.RegisterType((*PortIdentifier)(nil), "nodeservice.PortIdentifier")
	proto.RegisterType((*NodeIdentifier)(nil), "nodeservice.NodeIdentifier")
	proto.RegisterType((*RequestData)(nil), "nodeservice.RequestData")
	proto.RegisterEnum("nodeservice.LinkType", LinkType_name, LinkType_value)
	proto.RegisterEnum("nodeservice.NodeDescription_AttachedPortDescription_PortType", NodeDescription_AttachedPortDescription_PortType_name, NodeDescription_AttachedPortDescription_PortType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeService service

type NodeServiceClient interface {
	CreateNodes(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ModifyResponse, error)
	UpdateNodes(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ModifyResponse, error)
	DeleteNodes(ctx context.Context, in *Identifiers, opts ...grpc.CallOption) (*ModifyResponse, error)
	GetNodes(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	Process(ctx context.Context, in *Identifiers, opts ...grpc.CallOption) (*ModifyResponse, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*ModifyResponse, error)
	GetDescription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceDescription, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) CreateNodes(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*ModifyResponse, error) {
	out := new(ModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/CreateNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateNodes(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ModifyResponse, error) {
	out := new(ModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/UpdateNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteNodes(ctx context.Context, in *Identifiers, opts ...grpc.CallOption) (*ModifyResponse, error) {
	out := new(ModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/DeleteNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodes(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/GetNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Process(ctx context.Context, in *Identifiers, opts ...grpc.CallOption) (*ModifyResponse, error) {
	out := new(ModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/Process", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*ModifyResponse, error) {
	out := new(ModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/Link", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetDescription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceDescription, error) {
	out := new(ServiceDescription)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/GetDescription", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeService service

type NodeServiceServer interface {
	CreateNodes(context.Context, *CreateRequest) (*ModifyResponse, error)
	UpdateNodes(context.Context, *UpdateRequest) (*ModifyResponse, error)
	DeleteNodes(context.Context, *Identifiers) (*ModifyResponse, error)
	GetNodes(context.Context, *GetStateRequest) (*StateResponse, error)
	Process(context.Context, *Identifiers) (*ModifyResponse, error)
	Link(context.Context, *LinkRequest) (*ModifyResponse, error)
	GetDescription(context.Context, *Empty) (*ServiceDescription, error)
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_CreateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/CreateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateNodes(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/UpdateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateNodes(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/DeleteNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteNodes(ctx, req.(*Identifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodes(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Process(ctx, req.(*Identifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/GetDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetDescription(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodeservice.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNodes",
			Handler:    _NodeService_CreateNodes_Handler,
		},
		{
			MethodName: "UpdateNodes",
			Handler:    _NodeService_UpdateNodes_Handler,
		},
		{
			MethodName: "DeleteNodes",
			Handler:    _NodeService_DeleteNodes_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _NodeService_GetNodes_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _NodeService_Process_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _NodeService_Link_Handler,
		},
		{
			MethodName: "GetDescription",
			Handler:    _NodeService_GetDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_service.proto",
}

func init() { proto.RegisterFile("node_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5d, 0x6f, 0xe3, 0x44,
	0x17, 0xae, 0xed, 0xa4, 0x4d, 0x8e, 0x93, 0x34, 0x3b, 0x7a, 0x77, 0xdf, 0xe0, 0x5d, 0x89, 0xca,
	0x82, 0xa5, 0xa0, 0xdd, 0x48, 0x1b, 0xb8, 0x40, 0xa5, 0x1f, 0xb4, 0x89, 0xfb, 0xc1, 0xb6, 0x69,
	0x71, 0x52, 0x40, 0x7b, 0x53, 0xb9, 0xf1, 0xb4, 0x3b, 0x34, 0xb5, 0xb3, 0xb6, 0xb3, 0xb4, 0x12,
	0xbf, 0x85, 0x2b, 0x2e, 0xf6, 0x9e, 0x7f, 0x80, 0x84, 0xe0, 0xb7, 0x70, 0xcb, 0x35, 0x02, 0xcd,
	0x8c, 0xed, 0xcc, 0x24, 0x6e, 0xd2, 0xee, 0x72, 0xe7, 0x39, 0xf3, 0x3c, 0xcf, 0x9c, 0x8f, 0x99,
	0x33, 0x63, 0x40, 0x9e, 0xef, 0xe2, 0x93, 0x10, 0x07, 0xaf, 0x49, 0x0f, 0xd7, 0x07, 0x81, 0x1f,
	0xf9, 0x48, 0xa7, 0xb6, 0xd8, 0x64, 0x2e, 0x40, 0xde, 0xba, 0x1c, 0x44, 0xd7, 0xe6, 0x1b, 0x15,
	0xca, 0x9d, 0xc8, 0x89, 0xb0, 0x8d, 0xc3, 0x81, 0xef, 0x85, 0x18, 0x3d, 0x85, 0xdc, 0xa9, 0x13,
	0xe2, 0x9a, 0xb2, 0xa4, 0x2c, 0xeb, 0x8d, 0xf7, 0xea, 0x02, 0xad, 0xbe, 0xe5, 0x84, 0x29, 0xd0,
	0x66, 0x30, 0xb4, 0x06, 0x79, 0x12, 0xe1, 0xcb, 0xb0, 0xa6, 0x2e, 0x69, 0xcb, 0x7a, 0xe3, 0x23,
	0x09, 0x2f, 0x29, 0xd7, 0x8f, 0x3d, 0x12, 0xa5, 0x6c, 0xce, 0x32, 0xde, 0x28, 0x50, 0x12, 0xed,
	0x77, 0x5d, 0xfe, 0x0b, 0x00, 0xe2, 0x62, 0x2f, 0x22, 0x67, 0x04, 0x07, 0x35, 0x95, 0x91, 0x1e,
	0x4a, 0xa4, 0xb6, 0xef, 0xe2, 0xbd, 0x14, 0x62, 0x0b, 0x70, 0xf4, 0x04, 0xf2, 0x21, 0xf5, 0xb0,
	0xa6, 0x31, 0xde, 0x83, 0x09, 0x1e, 0xf7, 0x9f, 0x83, 0xcc, 0xbf, 0x15, 0xa8, 0x1c, 0xf8, 0x2e,
	0x39, 0xbb, 0x7e, 0x5b, 0x67, 0xd7, 0xe5, 0x5c, 0x2d, 0x4b, 0x78, 0x59, 0x3a, 0x33, 0x59, 0x3f,
	0x8e, 0xe5, 0x6a, 0x0d, 0xf4, 0x51, 0x34, 0x61, 0x4d, 0x61, 0xaa, 0x53, 0xa3, 0x17, 0xf1, 0xa9,
	0xf7, 0xea, 0xad, 0xbc, 0x37, 0x77, 0xa1, 0x24, 0x5a, 0xd1, 0x03, 0x98, 0xa7, 0x89, 0x19, 0x86,
	0x2c, 0xfc, 0xbc, 0x1d, 0x8f, 0xd0, 0x12, 0xe8, 0x2e, 0x0e, 0x7b, 0x01, 0x19, 0x44, 0xc4, 0xf7,
	0x98, 0x7a, 0xd1, 0x16, 0x4d, 0xe6, 0x1f, 0x1a, 0x14, 0xd3, 0xf4, 0x22, 0x04, 0x39, 0xcf, 0xb9,
	0xe4, 0x49, 0x2c, 0xda, 0xec, 0x1b, 0x35, 0xa1, 0xe8, 0x0d, 0x2f, 0xbf, 0x71, 0xfa, 0x43, 0x9c,
	0x64, 0xeb, 0xc3, 0xec, 0xea, 0xd4, 0xdb, 0x09, 0xce, 0xf2, 0xa2, 0xe0, 0xda, 0x1e, 0xf1, 0xd0,
	0x3e, 0x94, 0xc2, 0x28, 0x20, 0xde, 0x79, 0xac, 0xa3, 0x65, 0x64, 0x7d, 0xa4, 0xd3, 0x11, 0xa0,
	0x5c, 0x4a, 0x62, 0xa3, 0x2f, 0xa1, 0xd0, 0x7b, 0x49, 0xfa, 0x6e, 0x80, 0xbd, 0x5a, 0x8e, 0x29,
	0x7d, 0x70, 0x83, 0x52, 0x33, 0x86, 0x71, 0x95, 0x94, 0x65, 0xac, 0x42, 0x45, 0x76, 0x16, 0x55,
	0x41, 0xbb, 0xc0, 0xd7, 0x71, 0xe4, 0xf4, 0x13, 0xfd, 0x0f, 0xf2, 0xaf, 0x29, 0x80, 0xa5, 0x4d,
	0xb1, 0xf9, 0x60, 0x45, 0xfd, 0x5c, 0x31, 0x36, 0xe0, 0xde, 0x84, 0x8b, 0xb3, 0x04, 0x8a, 0xa2,
	0x40, 0x07, 0xca, 0x92, 0x67, 0x19, 0xe4, 0x27, 0x22, 0x79, 0xca, 0x81, 0x48, 0x45, 0xcd, 0xef,
	0x01, 0x75, 0xf8, 0x7c, 0x6b, 0x54, 0xe0, 0xf1, 0x2d, 0xa0, 0x4c, 0x6c, 0x01, 0xd4, 0x80, 0x3c,
	0xd3, 0x8e, 0x8b, 0xfb, 0x68, 0x62, 0x25, 0x41, 0xce, 0xe6, 0x50, 0xf3, 0xe7, 0x1c, 0x2c, 0x8e,
	0x4d, 0x21, 0x03, 0x0a, 0xd4, 0xd4, 0xbd, 0x1e, 0x24, 0x1b, 0x28, 0x1d, 0x23, 0x1b, 0x8a, 0x74,
	0xe3, 0x1e, 0xf9, 0x41, 0x94, 0xac, 0xf3, 0xd9, 0xb4, 0x75, 0xea, 0x9b, 0x51, 0xe4, 0xf4, 0x5e,
	0x62, 0x97, 0x32, 0xc4, 0xf5, 0x47, 0x32, 0xe8, 0x10, 0xca, 0x3d, 0xdf, 0x8b, 0xf0, 0x55, 0xc4,
	0x52, 0x91, 0x6c, 0xaa, 0x8f, 0xa7, 0xea, 0x36, 0x05, 0x86, 0x2d, 0xf3, 0x8d, 0x17, 0x50, 0x12,
	0xa7, 0xd1, 0x57, 0x90, 0x1f, 0x30, 0x87, 0x95, 0x77, 0x70, 0x98, 0x4b, 0x18, 0x7f, 0x29, 0xf0,
	0xff, 0x1b, 0x20, 0x68, 0x7d, 0xb2, 0x44, 0xe3, 0x65, 0x18, 0x57, 0x95, 0x0a, 0xf8, 0x35, 0xe4,
	0x22, 0x9a, 0x74, 0xba, 0x53, 0x2a, 0x8d, 0xb5, 0xb7, 0x71, 0x93, 0x2d, 0x40, 0x2b, 0x65, 0x33,
	0x29, 0xd3, 0x82, 0x42, 0x62, 0x41, 0x45, 0xc8, 0xef, 0xb5, 0x8f, 0x8e, 0xbb, 0xd5, 0x39, 0x04,
	0x30, 0x7f, 0x78, 0xdc, 0xa5, 0xdf, 0x0a, 0xd2, 0x61, 0xa1, 0x6d, 0x1d, 0x77, 0xed, 0xcd, 0xfd,
	0xaa, 0x8a, 0xee, 0xc3, 0xbd, 0xe6, 0x61, 0xbb, 0x6b, 0x7d, 0xd7, 0x3d, 0x69, 0x59, 0x47, 0x56,
	0xbb, 0x65, 0xb5, 0xbb, 0x55, 0xcd, 0x6c, 0xc2, 0xe2, 0x78, 0xb0, 0x0f, 0x60, 0x7e, 0x10, 0xe0,
	0x33, 0x72, 0x15, 0xef, 0x91, 0x78, 0x84, 0x6a, 0xb0, 0x40, 0xc2, 0x83, 0x61, 0x3f, 0x22, 0x2c,
	0x8e, 0x82, 0x9d, 0x0c, 0xcd, 0x3f, 0x15, 0xd0, 0xf7, 0x89, 0x77, 0x61, 0xe3, 0x57, 0x43, 0x1c,
	0x46, 0x68, 0x25, 0x69, 0xdd, 0x4a, 0xc6, 0xd1, 0x17, 0x80, 0x71, 0xdf, 0x66, 0xdf, 0x49, 0xdb,
	0xfe, 0x49, 0x01, 0x5d, 0x30, 0xa3, 0x67, 0x50, 0xe8, 0x13, 0xef, 0x22, 0xdd, 0xb3, 0x95, 0xc6,
	0xfd, 0x09, 0x39, 0x96, 0x96, 0x14, 0x86, 0x9e, 0x82, 0x46, 0xdc, 0x67, 0x99, 0xf7, 0x1b, 0x8d,
	0x55, 0xe8, 0xf0, 0x14, 0xc7, 0xe1, 0x8d, 0xf8, 0x5a, 0x9b, 0x05, 0x6f, 0x98, 0xbf, 0x2b, 0x50,
	0x3e, 0x1e, 0xb8, 0xec, 0xae, 0xe6, 0x2e, 0xae, 0xca, 0xe1, 0x3e, 0x96, 0x24, 0x24, 0x68, 0x56,
	0xc0, 0x57, 0x72, 0xbc, 0xf2, 0x1d, 0xad, 0xdc, 0xf5, 0x8e, 0xce, 0xb9, 0x4e, 0xe4, 0xc4, 0xa1,
	0xd7, 0x24, 0x5a, 0xbc, 0x40, 0xcb, 0x89, 0x1c, 0x9b, 0xa1, 0xcc, 0xdf, 0x14, 0x58, 0xdc, 0xc1,
	0xf1, 0x49, 0x8b, 0x97, 0x5f, 0x97, 0x63, 0x91, 0xfb, 0xff, 0x18, 0x38, 0x2b, 0x9a, 0xe0, 0x3f,
	0x8c, 0xe6, 0x31, 0x54, 0x02, 0xfc, 0x6a, 0x48, 0x02, 0xec, 0x6e, 0x13, 0xdc, 0x77, 0x79, 0x5f,
	0x2a, 0xda, 0x63, 0x56, 0xf3, 0x57, 0x05, 0xca, 0xcd, 0x00, 0xdf, 0xb6, 0x22, 0x12, 0x34, 0x2b,
	0x86, 0x50, 0x8e, 0xc1, 0x80, 0x02, 0xa5, 0xb7, 0x47, 0xd7, 0x6e, 0x3a, 0x4e, 0xe6, 0xba, 0xc9,
	0xe1, 0x8e, 0xe7, 0xd8, 0x36, 0x4c, 0x8a, 0xa1, 0xdd, 0xaa, 0x18, 0xab, 0xa0, 0xef, 0x49, 0xcf,
	0x0d, 0x8d, 0xb8, 0xb7, 0x7a, 0xa5, 0x50, 0x9c, 0xe9, 0x43, 0x45, 0xde, 0xab, 0xa8, 0x09, 0x15,
	0x4f, 0x02, 0xde, 0x26, 0xfb, 0x63, 0x14, 0x7a, 0xe4, 0x69, 0x73, 0xec, 0x3a, 0xe7, 0x71, 0x74,
	0xc9, 0xd0, 0xa4, 0xd7, 0xb3, 0x8c, 0xad, 0x80, 0x4a, 0xdc, 0xf8, 0x75, 0xa3, 0x12, 0x77, 0x5a,
	0x6a, 0xcc, 0x5f, 0x54, 0xd0, 0x85, 0x14, 0xd0, 0x7b, 0xd8, 0xdd, 0x0c, 0xce, 0x79, 0xbc, 0x8a,
	0xcd, 0x07, 0xd4, 0x1a, 0x32, 0x2b, 0x2f, 0x3b, 0x1f, 0xa0, 0x0d, 0x58, 0x70, 0x9f, 0xff, 0xe0,
	0x50, 0xbb, 0x96, 0xf1, 0xd6, 0x11, 0x64, 0xeb, 0x2d, 0x8e, 0xe3, 0x4f, 0x8b, 0x84, 0x45, 0x05,
	0xc2, 0x58, 0x20, 0x37, 0x43, 0xa0, 0x23, 0x09, 0xc4, 0x2c, 0x63, 0x05, 0x4a, 0xa2, 0xf2, 0x9d,
	0x1e, 0x26, 0x2b, 0x50, 0xea, 0xdc, 0x81, 0x2b, 0xbe, 0x49, 0x3e, 0xd9, 0x86, 0x42, 0xd2, 0xed,
	0x68, 0x9f, 0xef, 0xec, 0x1d, 0x1c, 0xed, 0x5b, 0xd5, 0x39, 0x54, 0x01, 0xf8, 0xd6, 0xda, 0x7c,
	0x7e, 0xb2, 0xbd, 0x67, 0x77, 0x68, 0xdf, 0x5f, 0x04, 0x9d, 0x8d, 0x3b, 0x56, 0xf3, 0xb0, 0xdd,
	0xaa, 0xaa, 0xa8, 0x0c, 0x45, 0x66, 0xd8, 0x3a, 0xec, 0xee, 0x56, 0xb5, 0xc6, 0x3f, 0x1a, 0xe8,
	0xec, 0x7d, 0xc2, 0x23, 0x46, 0xbb, 0xa0, 0xf3, 0x33, 0x41, 0x8d, 0x21, 0x32, 0x6e, 0x3e, 0x2d,
	0xc6, 0xc3, 0x29, 0xaf, 0x70, 0x73, 0x8e, 0x2a, 0xf1, 0x7e, 0x97, 0xa5, 0x24, 0x75, 0xc2, 0x59,
	0x4a, 0xdb, 0xa0, 0xb7, 0x70, 0x1f, 0x27, 0x4a, 0xf2, 0xe9, 0x11, 0x0e, 0xca, 0x6c, 0x9d, 0xc2,
	0x0e, 0x8e, 0xb8, 0xc8, 0xa3, 0x69, 0xcd, 0xcc, 0x30, 0x6e, 0xfe, 0x19, 0x33, 0xe7, 0xd0, 0x16,
	0x2c, 0x1c, 0x05, 0x7e, 0x0f, 0x87, 0xef, 0xe0, 0xcb, 0x06, 0xe4, 0x68, 0xfd, 0xc6, 0x04, 0x84,
	0xfb, 0x70, 0x96, 0xc0, 0x0e, 0x54, 0x76, 0xb0, 0x74, 0x57, 0x23, 0x89, 0xc0, 0xfe, 0x52, 0x8d,
	0xf7, 0xe5, 0x40, 0x26, 0x1e, 0x9c, 0xe6, 0xdc, 0x56, 0xee, 0x85, 0x3a, 0x38, 0x3d, 0x9d, 0x67,
	0xff, 0xba, 0x9f, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0xaa, 0x9b, 0x68, 0x01, 0x0f, 0x00,
	0x00,
}
