// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	node_service.proto
	network_service.proto

It has these top-level messages:
	Empty
	PortStateResponse
	NodeStateResponse
	PortModifyResponse
	NodeModifyResponse
	BaseResponse
	NodeState
	PortState
	State
	ServiceDescription
	NodeDescription
	PortDescription
	LinkRequest
	NodeUpdateRequest
	PortUpdateRequest
	PortStateRequest
	NodeStateRequest
	NodeCreateRequest
	PortIdentifier
	NodeIdentifiers
	NodeIdentifier
	RequestData
	NetworkDescription
	GraphStateResponse
	GraphModifyResponse
	GraphStateRequest
	GraphSolveRequest
	GraphProcessRequest
	SolutionOptions
	ProcessOptions
	GraphUpdateRequest
	GraphCreateRequest
	VariatorIdentifier
	NetworkIdentifier
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LinkType int32

const (
	LinkType_SIMPLE      LinkType = 0
	LinkType_WEAK_FIRST  LinkType = 1
	LinkType_WEAK_SECOND LinkType = 2
	LinkType_WEAK_BOTH   LinkType = 3
)

var LinkType_name = map[int32]string{
	0: "SIMPLE",
	1: "WEAK_FIRST",
	2: "WEAK_SECOND",
	3: "WEAK_BOTH",
}
var LinkType_value = map[string]int32{
	"SIMPLE":      0,
	"WEAK_FIRST":  1,
	"WEAK_SECOND": 2,
	"WEAK_BOTH":   3,
}

func (x LinkType) String() string {
	return proto.EnumName(LinkType_name, int32(x))
}
func (LinkType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeDescription_AttachedPortDescription_PortType int32

const (
	NodeDescription_AttachedPortDescription_INPUT             NodeDescription_AttachedPortDescription_PortType = 0
	NodeDescription_AttachedPortDescription_OUTPUT            NodeDescription_AttachedPortDescription_PortType = 1
	NodeDescription_AttachedPortDescription_NEUTRAL           NodeDescription_AttachedPortDescription_PortType = 2
	NodeDescription_AttachedPortDescription_CONTEXT_DEPENDENT NodeDescription_AttachedPortDescription_PortType = 3
)

var NodeDescription_AttachedPortDescription_PortType_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
	2: "NEUTRAL",
	3: "CONTEXT_DEPENDENT",
}
var NodeDescription_AttachedPortDescription_PortType_value = map[string]int32{
	"INPUT":             0,
	"OUTPUT":            1,
	"NEUTRAL":           2,
	"CONTEXT_DEPENDENT": 3,
}

func (x NodeDescription_AttachedPortDescription_PortType) String() string {
	return proto.EnumName(NodeDescription_AttachedPortDescription_PortType_name, int32(x))
}
func (NodeDescription_AttachedPortDescription_PortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 1, 0}
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PortStateResponse struct {
	Base  *BaseResponse                     `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Items []*PortStateResponse_UnitResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *PortStateResponse) Reset()                    { *m = PortStateResponse{} }
func (m *PortStateResponse) String() string            { return proto.CompactTextString(m) }
func (*PortStateResponse) ProtoMessage()               {}
func (*PortStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PortStateResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PortStateResponse) GetItems() []*PortStateResponse_UnitResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type PortStateResponse_UnitResponse struct {
	Base       *BaseResponse   `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Identifier *PortIdentifier `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	State      *PortState      `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
}

func (m *PortStateResponse_UnitResponse) Reset()         { *m = PortStateResponse_UnitResponse{} }
func (m *PortStateResponse_UnitResponse) String() string { return proto.CompactTextString(m) }
func (*PortStateResponse_UnitResponse) ProtoMessage()    {}
func (*PortStateResponse_UnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func (m *PortStateResponse_UnitResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PortStateResponse_UnitResponse) GetIdentifier() *PortIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *PortStateResponse_UnitResponse) GetState() *PortState {
	if m != nil {
		return m.State
	}
	return nil
}

type NodeStateResponse struct {
	Base  *BaseResponse                     `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Items []*NodeStateResponse_UnitResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *NodeStateResponse) Reset()                    { *m = NodeStateResponse{} }
func (m *NodeStateResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeStateResponse) ProtoMessage()               {}
func (*NodeStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeStateResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *NodeStateResponse) GetItems() []*NodeStateResponse_UnitResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type NodeStateResponse_UnitResponse struct {
	Base       *BaseResponse   `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Identifier *NodeIdentifier `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
	State      *NodeState      `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
}

func (m *NodeStateResponse_UnitResponse) Reset()         { *m = NodeStateResponse_UnitResponse{} }
func (m *NodeStateResponse_UnitResponse) String() string { return proto.CompactTextString(m) }
func (*NodeStateResponse_UnitResponse) ProtoMessage()    {}
func (*NodeStateResponse_UnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *NodeStateResponse_UnitResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *NodeStateResponse_UnitResponse) GetIdentifier() *NodeIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *NodeStateResponse_UnitResponse) GetState() *NodeState {
	if m != nil {
		return m.State
	}
	return nil
}

type PortModifyResponse struct {
	Base  *BaseResponse                      `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Items []*PortModifyResponse_UnitResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *PortModifyResponse) Reset()                    { *m = PortModifyResponse{} }
func (m *PortModifyResponse) String() string            { return proto.CompactTextString(m) }
func (*PortModifyResponse) ProtoMessage()               {}
func (*PortModifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PortModifyResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *PortModifyResponse) GetItems() []*PortModifyResponse_UnitResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type PortModifyResponse_UnitResponse struct {
	Identifier *PortIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Base       *BaseResponse   `protobuf:"bytes,2,opt,name=base" json:"base,omitempty"`
}

func (m *PortModifyResponse_UnitResponse) Reset()         { *m = PortModifyResponse_UnitResponse{} }
func (m *PortModifyResponse_UnitResponse) String() string { return proto.CompactTextString(m) }
func (*PortModifyResponse_UnitResponse) ProtoMessage()    {}
func (*PortModifyResponse_UnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

func (m *PortModifyResponse_UnitResponse) GetIdentifier() *PortIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *PortModifyResponse_UnitResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type NodeModifyResponse struct {
	Base  *BaseResponse                      `protobuf:"bytes,1,opt,name=base" json:"base,omitempty"`
	Items []*NodeModifyResponse_UnitResponse `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
}

func (m *NodeModifyResponse) Reset()                    { *m = NodeModifyResponse{} }
func (m *NodeModifyResponse) String() string            { return proto.CompactTextString(m) }
func (*NodeModifyResponse) ProtoMessage()               {}
func (*NodeModifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NodeModifyResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *NodeModifyResponse) GetItems() []*NodeModifyResponse_UnitResponse {
	if m != nil {
		return m.Items
	}
	return nil
}

type NodeModifyResponse_UnitResponse struct {
	// multiple nodes for link request
	Identifiers []*NodeIdentifier `protobuf:"bytes,1,rep,name=identifiers" json:"identifiers,omitempty"`
	Base        *BaseResponse     `protobuf:"bytes,2,opt,name=base" json:"base,omitempty"`
}

func (m *NodeModifyResponse_UnitResponse) Reset()         { *m = NodeModifyResponse_UnitResponse{} }
func (m *NodeModifyResponse_UnitResponse) String() string { return proto.CompactTextString(m) }
func (*NodeModifyResponse_UnitResponse) ProtoMessage()    {}
func (*NodeModifyResponse_UnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

func (m *NodeModifyResponse_UnitResponse) GetIdentifiers() []*NodeIdentifier {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *NodeModifyResponse_UnitResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

type BaseResponse struct {
	Status      int32    `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Messages    []string `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
}

func (m *BaseResponse) Reset()                    { *m = BaseResponse{} }
func (m *BaseResponse) String() string            { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()               {}
func (*BaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BaseResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BaseResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BaseResponse) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type NodeState struct {
	Name       string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	State      *State                `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	PortStates []*PortState          `protobuf:"bytes,3,rep,name=portStates" json:"portStates,omitempty"`
	Children   map[string]*NodeState `protobuf:"bytes,4,rep,name=children" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *NodeState) Reset()                    { *m = NodeState{} }
func (m *NodeState) String() string            { return proto.CompactTextString(m) }
func (*NodeState) ProtoMessage()               {}
func (*NodeState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NodeState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeState) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *NodeState) GetPortStates() []*PortState {
	if m != nil {
		return m.PortStates
	}
	return nil
}

func (m *NodeState) GetChildren() map[string]*NodeState {
	if m != nil {
		return m.Children
	}
	return nil
}

type PortState struct {
	Tag   string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	State *State `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
}

func (m *PortState) Reset()                    { *m = PortState{} }
func (m *PortState) String() string            { return proto.CompactTextString(m) }
func (*PortState) ProtoMessage()               {}
func (*PortState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PortState) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *PortState) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

type State struct {
	NumValues    map[string]float64 `protobuf:"bytes,1,rep,name=numValues" json:"numValues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	StringValues map[string]string  `protobuf:"bytes,2,rep,name=stringValues" json:"stringValues,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *State) GetNumValues() map[string]float64 {
	if m != nil {
		return m.NumValues
	}
	return nil
}

func (m *State) GetStringValues() map[string]string {
	if m != nil {
		return m.StringValues
	}
	return nil
}

type ServiceDescription struct {
	Description string             `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Nodes       []*NodeDescription `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *ServiceDescription) Reset()                    { *m = ServiceDescription{} }
func (m *ServiceDescription) String() string            { return proto.CompactTextString(m) }
func (*ServiceDescription) ProtoMessage()               {}
func (*ServiceDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ServiceDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ServiceDescription) GetNodes() []*NodeDescription {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeDescription struct {
	NodeType      string                                     `protobuf:"bytes,1,opt,name=NodeType" json:"NodeType,omitempty"`
	BasePorts     []*NodeDescription_AttachedPortDescription `protobuf:"bytes,2,rep,name=basePorts" json:"basePorts,omitempty"`
	ContextStates []*NodeDescription_ContextState            `protobuf:"bytes,3,rep,name=contextStates" json:"contextStates,omitempty"`
}

func (m *NodeDescription) Reset()                    { *m = NodeDescription{} }
func (m *NodeDescription) String() string            { return proto.CompactTextString(m) }
func (*NodeDescription) ProtoMessage()               {}
func (*NodeDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *NodeDescription) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *NodeDescription) GetBasePorts() []*NodeDescription_AttachedPortDescription {
	if m != nil {
		return m.BasePorts
	}
	return nil
}

func (m *NodeDescription) GetContextStates() []*NodeDescription_ContextState {
	if m != nil {
		return m.ContextStates
	}
	return nil
}

type NodeDescription_ContextState struct {
	Ports []*NodeDescription_AttachedPortDescription `protobuf:"bytes,1,rep,name=ports" json:"ports,omitempty"`
}

func (m *NodeDescription_ContextState) Reset()         { *m = NodeDescription_ContextState{} }
func (m *NodeDescription_ContextState) String() string { return proto.CompactTextString(m) }
func (*NodeDescription_ContextState) ProtoMessage()    {}
func (*NodeDescription_ContextState) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

func (m *NodeDescription_ContextState) GetPorts() []*NodeDescription_AttachedPortDescription {
	if m != nil {
		return m.Ports
	}
	return nil
}

type NodeDescription_AttachedPortDescription struct {
	Description *PortDescription                                 `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Type        NodeDescription_AttachedPortDescription_PortType `protobuf:"varint,2,opt,name=type,enum=nodeservice.NodeDescription_AttachedPortDescription_PortType" json:"type,omitempty"`
}

func (m *NodeDescription_AttachedPortDescription) Reset() {
	*m = NodeDescription_AttachedPortDescription{}
}
func (m *NodeDescription_AttachedPortDescription) String() string { return proto.CompactTextString(m) }
func (*NodeDescription_AttachedPortDescription) ProtoMessage()    {}
func (*NodeDescription_AttachedPortDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 1}
}

func (m *NodeDescription_AttachedPortDescription) GetDescription() *PortDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *NodeDescription_AttachedPortDescription) GetType() NodeDescription_AttachedPortDescription_PortType {
	if m != nil {
		return m.Type
	}
	return NodeDescription_AttachedPortDescription_INPUT
}

type PortDescription struct {
	Prefix  string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	IsMulti bool   `protobuf:"varint,2,opt,name=isMulti" json:"isMulti,omitempty"`
}

func (m *PortDescription) Reset()                    { *m = PortDescription{} }
func (m *PortDescription) String() string            { return proto.CompactTextString(m) }
func (*PortDescription) ProtoMessage()               {}
func (*PortDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PortDescription) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *PortDescription) GetIsMulti() bool {
	if m != nil {
		return m.IsMulti
	}
	return false
}

type LinkRequest struct {
	Items []*LinkRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *LinkRequest) Reset()                    { *m = LinkRequest{} }
func (m *LinkRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()               {}
func (*LinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *LinkRequest) GetItems() []*LinkRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type LinkRequest_UnitRequest struct {
	LinkType LinkType        `protobuf:"varint,1,opt,name=linkType,enum=nodeservice.LinkType" json:"linkType,omitempty"`
	Id1      *PortIdentifier `protobuf:"bytes,2,opt,name=id1" json:"id1,omitempty"`
	Id2      *PortIdentifier `protobuf:"bytes,3,opt,name=id2" json:"id2,omitempty"`
}

func (m *LinkRequest_UnitRequest) Reset()                    { *m = LinkRequest_UnitRequest{} }
func (m *LinkRequest_UnitRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest_UnitRequest) ProtoMessage()               {}
func (*LinkRequest_UnitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

func (m *LinkRequest_UnitRequest) GetLinkType() LinkType {
	if m != nil {
		return m.LinkType
	}
	return LinkType_SIMPLE
}

func (m *LinkRequest_UnitRequest) GetId1() *PortIdentifier {
	if m != nil {
		return m.Id1
	}
	return nil
}

func (m *LinkRequest_UnitRequest) GetId2() *PortIdentifier {
	if m != nil {
		return m.Id2
	}
	return nil
}

type NodeUpdateRequest struct {
	Items []*NodeUpdateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *NodeUpdateRequest) Reset()                    { *m = NodeUpdateRequest{} }
func (m *NodeUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeUpdateRequest) ProtoMessage()               {}
func (*NodeUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *NodeUpdateRequest) GetItems() []*NodeUpdateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type NodeUpdateRequest_UnitRequest struct {
	Identifier *NodeIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Data       *RequestData    `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *NodeUpdateRequest_UnitRequest) Reset()         { *m = NodeUpdateRequest_UnitRequest{} }
func (m *NodeUpdateRequest_UnitRequest) String() string { return proto.CompactTextString(m) }
func (*NodeUpdateRequest_UnitRequest) ProtoMessage()    {}
func (*NodeUpdateRequest_UnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 0}
}

func (m *NodeUpdateRequest_UnitRequest) GetIdentifier() *NodeIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *NodeUpdateRequest_UnitRequest) GetData() *RequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PortUpdateRequest struct {
	Items []*PortUpdateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *PortUpdateRequest) Reset()                    { *m = PortUpdateRequest{} }
func (m *PortUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*PortUpdateRequest) ProtoMessage()               {}
func (*PortUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PortUpdateRequest) GetItems() []*PortUpdateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type PortUpdateRequest_UnitRequest struct {
	Identifier *PortIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	State      *PortState      `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
}

func (m *PortUpdateRequest_UnitRequest) Reset()         { *m = PortUpdateRequest_UnitRequest{} }
func (m *PortUpdateRequest_UnitRequest) String() string { return proto.CompactTextString(m) }
func (*PortUpdateRequest_UnitRequest) ProtoMessage()    {}
func (*PortUpdateRequest_UnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14, 0}
}

func (m *PortUpdateRequest_UnitRequest) GetIdentifier() *PortIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *PortUpdateRequest_UnitRequest) GetState() *PortState {
	if m != nil {
		return m.State
	}
	return nil
}

type PortStateRequest struct {
	Items []*PortStateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *PortStateRequest) Reset()                    { *m = PortStateRequest{} }
func (m *PortStateRequest) String() string            { return proto.CompactTextString(m) }
func (*PortStateRequest) ProtoMessage()               {}
func (*PortStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PortStateRequest) GetItems() []*PortStateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type PortStateRequest_UnitRequest struct {
	Identifier *PortIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// optional field neccessary if complete state is not required
	RequiredFields []string `protobuf:"bytes,2,rep,name=requiredFields" json:"requiredFields,omitempty"`
}

func (m *PortStateRequest_UnitRequest) Reset()         { *m = PortStateRequest_UnitRequest{} }
func (m *PortStateRequest_UnitRequest) String() string { return proto.CompactTextString(m) }
func (*PortStateRequest_UnitRequest) ProtoMessage()    {}
func (*PortStateRequest_UnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 0}
}

func (m *PortStateRequest_UnitRequest) GetIdentifier() *PortIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *PortStateRequest_UnitRequest) GetRequiredFields() []string {
	if m != nil {
		return m.RequiredFields
	}
	return nil
}

type NodeStateRequest struct {
	Items []*NodeStateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *NodeStateRequest) Reset()                    { *m = NodeStateRequest{} }
func (m *NodeStateRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeStateRequest) ProtoMessage()               {}
func (*NodeStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *NodeStateRequest) GetItems() []*NodeStateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type NodeStateRequest_UnitRequest struct {
	Identifier *NodeIdentifier `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	// optional field neccessary if complete state is not required
	RequiredFields []string `protobuf:"bytes,2,rep,name=requiredFields" json:"requiredFields,omitempty"`
}

func (m *NodeStateRequest_UnitRequest) Reset()         { *m = NodeStateRequest_UnitRequest{} }
func (m *NodeStateRequest_UnitRequest) String() string { return proto.CompactTextString(m) }
func (*NodeStateRequest_UnitRequest) ProtoMessage()    {}
func (*NodeStateRequest_UnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16, 0}
}

func (m *NodeStateRequest_UnitRequest) GetIdentifier() *NodeIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *NodeStateRequest_UnitRequest) GetRequiredFields() []string {
	if m != nil {
		return m.RequiredFields
	}
	return nil
}

type NodeCreateRequest struct {
	Items []*NodeCreateRequest_UnitRequest `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *NodeCreateRequest) Reset()                    { *m = NodeCreateRequest{} }
func (m *NodeCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*NodeCreateRequest) ProtoMessage()               {}
func (*NodeCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *NodeCreateRequest) GetItems() []*NodeCreateRequest_UnitRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type NodeCreateRequest_UnitRequest struct {
	NodeName string       `protobuf:"bytes,1,opt,name=nodeName" json:"nodeName,omitempty"`
	NodeType string       `protobuf:"bytes,2,opt,name=nodeType" json:"nodeType,omitempty"`
	Data     *RequestData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *NodeCreateRequest_UnitRequest) Reset()         { *m = NodeCreateRequest_UnitRequest{} }
func (m *NodeCreateRequest_UnitRequest) String() string { return proto.CompactTextString(m) }
func (*NodeCreateRequest_UnitRequest) ProtoMessage()    {}
func (*NodeCreateRequest_UnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{17, 0}
}

func (m *NodeCreateRequest_UnitRequest) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *NodeCreateRequest_UnitRequest) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *NodeCreateRequest_UnitRequest) GetData() *RequestData {
	if m != nil {
		return m.Data
	}
	return nil
}

type PortIdentifier struct {
	NodeIdentifier *NodeIdentifier `protobuf:"bytes,1,opt,name=nodeIdentifier" json:"nodeIdentifier,omitempty"`
	NodeName       string          `protobuf:"bytes,2,opt,name=nodeName" json:"nodeName,omitempty"`
	PortTag        string          `protobuf:"bytes,3,opt,name=portTag" json:"portTag,omitempty"`
}

func (m *PortIdentifier) Reset()                    { *m = PortIdentifier{} }
func (m *PortIdentifier) String() string            { return proto.CompactTextString(m) }
func (*PortIdentifier) ProtoMessage()               {}
func (*PortIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PortIdentifier) GetNodeIdentifier() *NodeIdentifier {
	if m != nil {
		return m.NodeIdentifier
	}
	return nil
}

func (m *PortIdentifier) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *PortIdentifier) GetPortTag() string {
	if m != nil {
		return m.PortTag
	}
	return ""
}

type NodeIdentifiers struct {
	Ids []*NodeIdentifier `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *NodeIdentifiers) Reset()                    { *m = NodeIdentifiers{} }
func (m *NodeIdentifiers) String() string            { return proto.CompactTextString(m) }
func (*NodeIdentifiers) ProtoMessage()               {}
func (*NodeIdentifiers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *NodeIdentifiers) GetIds() []*NodeIdentifier {
	if m != nil {
		return m.Ids
	}
	return nil
}

type NodeIdentifier struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	NodeType string `protobuf:"bytes,2,opt,name=nodeType" json:"nodeType,omitempty"`
}

func (m *NodeIdentifier) Reset()                    { *m = NodeIdentifier{} }
func (m *NodeIdentifier) String() string            { return proto.CompactTextString(m) }
func (*NodeIdentifier) ProtoMessage()               {}
func (*NodeIdentifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *NodeIdentifier) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeIdentifier) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

type RequestData struct {
	DArgs   []float64          `protobuf:"fixed64,1,rep,packed,name=dArgs" json:"dArgs,omitempty"`
	SArgs   []string           `protobuf:"bytes,2,rep,name=sArgs" json:"sArgs,omitempty"`
	DKwargs map[string]float64 `protobuf:"bytes,3,rep,name=dKwargs" json:"dKwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	SKwargs map[string]string  `protobuf:"bytes,4,rep,name=sKwargs" json:"sKwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *RequestData) Reset()                    { *m = RequestData{} }
func (m *RequestData) String() string            { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()               {}
func (*RequestData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RequestData) GetDArgs() []float64 {
	if m != nil {
		return m.DArgs
	}
	return nil
}

func (m *RequestData) GetSArgs() []string {
	if m != nil {
		return m.SArgs
	}
	return nil
}

func (m *RequestData) GetDKwargs() map[string]float64 {
	if m != nil {
		return m.DKwargs
	}
	return nil
}

func (m *RequestData) GetSKwargs() map[string]string {
	if m != nil {
		return m.SKwargs
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "nodeservice.Empty")
	proto.RegisterType((*PortStateResponse)(nil), "nodeservice.PortStateResponse")
	proto.RegisterType((*PortStateResponse_UnitResponse)(nil), "nodeservice.PortStateResponse.UnitResponse")
	proto.RegisterType((*NodeStateResponse)(nil), "nodeservice.NodeStateResponse")
	proto.RegisterType((*NodeStateResponse_UnitResponse)(nil), "nodeservice.NodeStateResponse.UnitResponse")
	proto.RegisterType((*PortModifyResponse)(nil), "nodeservice.PortModifyResponse")
	proto.RegisterType((*PortModifyResponse_UnitResponse)(nil), "nodeservice.PortModifyResponse.UnitResponse")
	proto.RegisterType((*NodeModifyResponse)(nil), "nodeservice.NodeModifyResponse")
	proto.RegisterType((*NodeModifyResponse_UnitResponse)(nil), "nodeservice.NodeModifyResponse.UnitResponse")
	proto.RegisterType((*BaseResponse)(nil), "nodeservice.BaseResponse")
	proto.RegisterType((*NodeState)(nil), "nodeservice.NodeState")
	proto.RegisterType((*PortState)(nil), "nodeservice.PortState")
	proto.RegisterType((*State)(nil), "nodeservice.State")
	proto.RegisterType((*ServiceDescription)(nil), "nodeservice.ServiceDescription")
	proto.RegisterType((*NodeDescription)(nil), "nodeservice.NodeDescription")
	proto.RegisterType((*NodeDescription_ContextState)(nil), "nodeservice.NodeDescription.ContextState")
	proto.RegisterType((*NodeDescription_AttachedPortDescription)(nil), "nodeservice.NodeDescription.AttachedPortDescription")
	proto.RegisterType((*PortDescription)(nil), "nodeservice.PortDescription")
	proto.RegisterType((*LinkRequest)(nil), "nodeservice.LinkRequest")
	proto.RegisterType((*LinkRequest_UnitRequest)(nil), "nodeservice.LinkRequest.UnitRequest")
	proto.RegisterType((*NodeUpdateRequest)(nil), "nodeservice.NodeUpdateRequest")
	proto.RegisterType((*NodeUpdateRequest_UnitRequest)(nil), "nodeservice.NodeUpdateRequest.UnitRequest")
	proto.RegisterType((*PortUpdateRequest)(nil), "nodeservice.PortUpdateRequest")
	proto.RegisterType((*PortUpdateRequest_UnitRequest)(nil), "nodeservice.PortUpdateRequest.UnitRequest")
	proto.RegisterType((*PortStateRequest)(nil), "nodeservice.PortStateRequest")
	proto.RegisterType((*PortStateRequest_UnitRequest)(nil), "nodeservice.PortStateRequest.UnitRequest")
	proto.RegisterType((*NodeStateRequest)(nil), "nodeservice.NodeStateRequest")
	proto.RegisterType((*NodeStateRequest_UnitRequest)(nil), "nodeservice.NodeStateRequest.UnitRequest")
	proto.RegisterType((*NodeCreateRequest)(nil), "nodeservice.NodeCreateRequest")
	proto.RegisterType((*NodeCreateRequest_UnitRequest)(nil), "nodeservice.NodeCreateRequest.UnitRequest")
	proto.RegisterType((*PortIdentifier)(nil), "nodeservice.PortIdentifier")
	proto.RegisterType((*NodeIdentifiers)(nil), "nodeservice.NodeIdentifiers")
	proto.RegisterType((*NodeIdentifier)(nil), "nodeservice.NodeIdentifier")
	proto.RegisterType((*RequestData)(nil), "nodeservice.RequestData")
	proto.RegisterEnum("nodeservice.LinkType", LinkType_name, LinkType_value)
	proto.RegisterEnum("nodeservice.NodeDescription_AttachedPortDescription_PortType", NodeDescription_AttachedPortDescription_PortType_name, NodeDescription_AttachedPortDescription_PortType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeService service

type NodeServiceClient interface {
	CreateNodes(ctx context.Context, in *NodeCreateRequest, opts ...grpc.CallOption) (*NodeModifyResponse, error)
	UpdateNodes(ctx context.Context, in *NodeUpdateRequest, opts ...grpc.CallOption) (*NodeModifyResponse, error)
	DeleteNodes(ctx context.Context, in *NodeIdentifiers, opts ...grpc.CallOption) (*NodeModifyResponse, error)
	GetNodesState(ctx context.Context, in *NodeStateRequest, opts ...grpc.CallOption) (*NodeStateResponse, error)
	GetPortsState(ctx context.Context, in *PortStateRequest, opts ...grpc.CallOption) (*PortStateResponse, error)
	SetPortsState(ctx context.Context, in *PortUpdateRequest, opts ...grpc.CallOption) (*PortModifyResponse, error)
	Process(ctx context.Context, in *NodeIdentifiers, opts ...grpc.CallOption) (*NodeModifyResponse, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*NodeModifyResponse, error)
	GetDescription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceDescription, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) CreateNodes(ctx context.Context, in *NodeCreateRequest, opts ...grpc.CallOption) (*NodeModifyResponse, error) {
	out := new(NodeModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/CreateNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) UpdateNodes(ctx context.Context, in *NodeUpdateRequest, opts ...grpc.CallOption) (*NodeModifyResponse, error) {
	out := new(NodeModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/UpdateNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) DeleteNodes(ctx context.Context, in *NodeIdentifiers, opts ...grpc.CallOption) (*NodeModifyResponse, error) {
	out := new(NodeModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/DeleteNodes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetNodesState(ctx context.Context, in *NodeStateRequest, opts ...grpc.CallOption) (*NodeStateResponse, error) {
	out := new(NodeStateResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/GetNodesState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetPortsState(ctx context.Context, in *PortStateRequest, opts ...grpc.CallOption) (*PortStateResponse, error) {
	out := new(PortStateResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/GetPortsState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) SetPortsState(ctx context.Context, in *PortUpdateRequest, opts ...grpc.CallOption) (*PortModifyResponse, error) {
	out := new(PortModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/SetPortsState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Process(ctx context.Context, in *NodeIdentifiers, opts ...grpc.CallOption) (*NodeModifyResponse, error) {
	out := new(NodeModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/Process", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*NodeModifyResponse, error) {
	out := new(NodeModifyResponse)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/Link", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetDescription(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServiceDescription, error) {
	out := new(ServiceDescription)
	err := grpc.Invoke(ctx, "/nodeservice.NodeService/GetDescription", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeService service

type NodeServiceServer interface {
	CreateNodes(context.Context, *NodeCreateRequest) (*NodeModifyResponse, error)
	UpdateNodes(context.Context, *NodeUpdateRequest) (*NodeModifyResponse, error)
	DeleteNodes(context.Context, *NodeIdentifiers) (*NodeModifyResponse, error)
	GetNodesState(context.Context, *NodeStateRequest) (*NodeStateResponse, error)
	GetPortsState(context.Context, *PortStateRequest) (*PortStateResponse, error)
	SetPortsState(context.Context, *PortUpdateRequest) (*PortModifyResponse, error)
	Process(context.Context, *NodeIdentifiers) (*NodeModifyResponse, error)
	Link(context.Context, *LinkRequest) (*NodeModifyResponse, error)
	GetDescription(context.Context, *Empty) (*ServiceDescription, error)
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_CreateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/CreateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateNodes(ctx, req.(*NodeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_UpdateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).UpdateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/UpdateNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).UpdateNodes(ctx, req.(*NodeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_DeleteNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).DeleteNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/DeleteNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).DeleteNodes(ctx, req.(*NodeIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetNodesState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodesState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/GetNodesState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodesState(ctx, req.(*NodeStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetPortsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetPortsState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/GetPortsState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetPortsState(ctx, req.(*PortStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_SetPortsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SetPortsState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/SetPortsState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SetPortsState(ctx, req.(*PortUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdentifiers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Process(ctx, req.(*NodeIdentifiers))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/Link",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Link(ctx, req.(*LinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservice.NodeService/GetDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetDescription(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodeservice.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNodes",
			Handler:    _NodeService_CreateNodes_Handler,
		},
		{
			MethodName: "UpdateNodes",
			Handler:    _NodeService_UpdateNodes_Handler,
		},
		{
			MethodName: "DeleteNodes",
			Handler:    _NodeService_DeleteNodes_Handler,
		},
		{
			MethodName: "GetNodesState",
			Handler:    _NodeService_GetNodesState_Handler,
		},
		{
			MethodName: "GetPortsState",
			Handler:    _NodeService_GetPortsState_Handler,
		},
		{
			MethodName: "SetPortsState",
			Handler:    _NodeService_SetPortsState_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _NodeService_Process_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _NodeService_Link_Handler,
		},
		{
			MethodName: "GetDescription",
			Handler:    _NodeService_GetDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node_service.proto",
}

func init() { proto.RegisterFile("node_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcf, 0x73, 0xdb, 0xc4,
	0x17, 0xb7, 0x64, 0x3b, 0xb6, 0x9e, 0x1c, 0xd7, 0xdd, 0xf9, 0xb6, 0x5f, 0x63, 0x4a, 0x09, 0x1a,
	0x60, 0xd2, 0xd2, 0x7a, 0xa6, 0x86, 0x61, 0x98, 0x40, 0xc9, 0x0f, 0xdb, 0x49, 0xd3, 0x26, 0x8e,
	0x91, 0x1d, 0x60, 0x7a, 0xc9, 0x28, 0xd6, 0xc6, 0x15, 0x71, 0x64, 0x57, 0x92, 0x4b, 0xc2, 0x70,
	0x63, 0x38, 0x71, 0xe2, 0xc6, 0x89, 0x13, 0x07, 0x8e, 0xcc, 0xf0, 0x47, 0x30, 0xc3, 0x85, 0x03,
	0xff, 0x05, 0x57, 0xfe, 0x01, 0x66, 0x77, 0x25, 0x65, 0x57, 0xb2, 0x1d, 0x39, 0xa4, 0xc3, 0x4d,
	0xbb, 0x7a, 0xef, 0xb3, 0xef, 0xf3, 0xd9, 0xf7, 0x76, 0x9f, 0x04, 0xc8, 0x1e, 0x9a, 0xf8, 0xc0,
	0xc5, 0xce, 0x0b, 0xab, 0x87, 0xab, 0x23, 0x67, 0xe8, 0x0d, 0x91, 0x4a, 0xe6, 0xfc, 0x29, 0x2d,
	0x07, 0xd9, 0xe6, 0xc9, 0xc8, 0x3b, 0xd3, 0x7e, 0x91, 0xe1, 0x7a, 0x7b, 0xe8, 0x78, 0x1d, 0xcf,
	0xf0, 0xb0, 0x8e, 0xdd, 0xd1, 0xd0, 0x76, 0x31, 0xba, 0x0f, 0x99, 0x43, 0xc3, 0xc5, 0x65, 0x69,
	0x49, 0x5a, 0x56, 0x6b, 0xaf, 0x54, 0x39, 0xd7, 0xea, 0x86, 0xe1, 0x86, 0x86, 0x3a, 0x35, 0x43,
	0xeb, 0x90, 0xb5, 0x3c, 0x7c, 0xe2, 0x96, 0xe5, 0xa5, 0xf4, 0xb2, 0x5a, 0x7b, 0x47, 0xb0, 0x8f,
	0xa1, 0x57, 0xf7, 0x6d, 0xcb, 0x0b, 0x11, 0x98, 0x67, 0xe5, 0x67, 0x09, 0x0a, 0xfc, 0xfc, 0xbc,
	0x21, 0x7c, 0x08, 0x60, 0x99, 0xd8, 0xf6, 0xac, 0x23, 0x0b, 0x3b, 0x65, 0x99, 0x3a, 0xbd, 0x1a,
	0x8b, 0x63, 0x3b, 0x34, 0xd1, 0x39, 0x73, 0x74, 0x0f, 0xb2, 0x2e, 0x89, 0xb0, 0x9c, 0xa6, 0x7e,
	0x37, 0xa7, 0xc4, 0xcf, 0x8c, 0xa8, 0x64, 0xad, 0xa1, 0x89, 0x5f, 0x9e, 0x64, 0x31, 0xf4, 0xff,
	0x48, 0x32, 0x12, 0xc7, 0x65, 0x24, 0x3b, 0x8f, 0xdf, 0x97, 0xec, 0x1b, 0x19, 0x10, 0xd1, 0x71,
	0x77, 0x68, 0x5a, 0x47, 0x67, 0x97, 0x0d, 0x78, 0x43, 0xd4, 0xec, 0x5e, 0x6c, 0x9b, 0x44, 0xf8,
	0x89, 0xa2, 0x7d, 0x15, 0xd1, 0x4c, 0x14, 0x41, 0x9a, 0x2f, 0x6f, 0x82, 0xf8, 0xe5, 0x44, 0xf1,
	0x6b, 0xdf, 0xca, 0x80, 0x88, 0x34, 0x2f, 0x51, 0x85, 0x38, 0xfc, 0x44, 0x15, 0xbe, 0x8e, 0xa8,
	0xf0, 0x10, 0xd4, 0x73, 0x5a, 0x6e, 0x59, 0xa2, 0xc8, 0x33, 0x73, 0x81, 0xb7, 0x9f, 0x57, 0x07,
	0x13, 0x0a, 0xfc, 0x2c, 0xba, 0x09, 0x0b, 0x24, 0x4d, 0xc6, 0x2e, 0x95, 0x20, 0xab, 0xfb, 0x23,
	0xb4, 0x04, 0xaa, 0x89, 0xdd, 0x9e, 0x63, 0x8d, 0x3c, 0x6b, 0x68, 0x53, 0x74, 0x45, 0xe7, 0xa7,
	0x50, 0x05, 0xf2, 0x27, 0xd8, 0x75, 0x8d, 0x3e, 0x76, 0xcb, 0xe9, 0xa5, 0xf4, 0xb2, 0xa2, 0x87,
	0x63, 0xed, 0x07, 0x19, 0x94, 0x30, 0x11, 0x11, 0x82, 0x8c, 0x6d, 0x9c, 0x30, 0x91, 0x15, 0x9d,
	0x3e, 0xa3, 0xe5, 0x20, 0x87, 0x59, 0xdc, 0x48, 0x88, 0x9b, 0xcf, 0x5f, 0xf4, 0x3e, 0xc0, 0x28,
	0x38, 0x06, 0xd8, 0x4a, 0xd3, 0x4f, 0x09, 0xce, 0x12, 0xad, 0x41, 0xbe, 0xf7, 0xcc, 0x1a, 0x98,
	0x0e, 0xb6, 0xcb, 0x19, 0xea, 0xf5, 0xe6, 0xe4, 0x42, 0xa9, 0xd6, 0x7d, 0xb3, 0xa6, 0xed, 0x39,
	0x67, 0x7a, 0xe8, 0x55, 0xe9, 0xc0, 0xa2, 0xf0, 0x0a, 0x95, 0x20, 0x7d, 0x8c, 0xcf, 0x7c, 0x1e,
	0xe4, 0x91, 0x94, 0xe2, 0x0b, 0x63, 0x30, 0x0e, 0x68, 0x4c, 0x2d, 0x45, 0x6a, 0xb4, 0x22, 0x7f,
	0x20, 0x69, 0x5b, 0xa0, 0x84, 0xf1, 0x12, 0x40, 0xcf, 0xe8, 0x07, 0x80, 0x9e, 0xd1, 0x4f, 0xae,
	0x8b, 0xf6, 0xbd, 0x0c, 0x59, 0x86, 0xb2, 0x0a, 0x8a, 0x3d, 0x3e, 0xf9, 0x94, 0x2c, 0x11, 0xe4,
	0xcf, 0x1b, 0x71, 0xbf, 0x6a, 0x2b, 0xb0, 0x61, 0x3c, 0xcf, 0x7d, 0xd0, 0x23, 0x28, 0xb8, 0x9e,
	0x63, 0xd9, 0x7d, 0x1f, 0x43, 0x9e, 0x20, 0x17, 0xc3, 0xe8, 0x70, 0x66, 0x0c, 0x46, 0xf0, 0xac,
	0x7c, 0x04, 0x45, 0x71, 0x99, 0x09, 0x9a, 0xfd, 0x8f, 0xd7, 0x4c, 0xe2, 0xb4, 0xa9, 0xac, 0xc2,
	0xf5, 0xd8, 0x02, 0x17, 0x01, 0x28, 0xbc, 0xb8, 0x5f, 0x00, 0xea, 0xb0, 0x78, 0x1b, 0x5c, 0xa6,
	0x46, 0x72, 0x59, 0x8a, 0xe7, 0x72, 0x0d, 0xb2, 0x94, 0xab, 0xcf, 0xfc, 0x56, 0x6c, 0x1b, 0x39,
	0x38, 0x9d, 0x99, 0x6a, 0x3f, 0x65, 0xe0, 0x5a, 0xe4, 0x15, 0xa9, 0x09, 0x32, 0xd5, 0x3d, 0x1b,
	0x05, 0xd9, 0x1e, 0x8e, 0x91, 0x0e, 0x0a, 0xa9, 0x40, 0xb2, 0xf9, 0xc1, 0x3a, 0xef, 0xcd, 0x5a,
	0xa7, 0xba, 0xee, 0x79, 0x46, 0xef, 0x19, 0x36, 0x89, 0x07, 0xbf, 0xfe, 0x39, 0x0c, 0xda, 0x83,
	0xc5, 0xde, 0xd0, 0xf6, 0xf0, 0xa9, 0x58, 0x1e, 0x77, 0x66, 0xe2, 0xd6, 0x39, 0x0f, 0x5d, 0xf4,
	0xaf, 0x3c, 0x85, 0x02, 0xff, 0x1a, 0x3d, 0x86, 0xec, 0x88, 0x06, 0x2c, 0xfd, 0x8b, 0x80, 0x19,
	0x44, 0xe5, 0x6f, 0x09, 0xfe, 0x3f, 0xc5, 0x04, 0x7d, 0x1c, 0xdf, 0xa2, 0xe8, 0x36, 0x44, 0x51,
	0x85, 0x0d, 0xfc, 0x04, 0x32, 0x1e, 0x11, 0x9d, 0x64, 0x44, 0xb1, 0xf6, 0xf0, 0x32, 0x61, 0xd2,
	0x05, 0xc8, 0x4e, 0xe9, 0x14, 0x4a, 0x6b, 0x42, 0x3e, 0x98, 0x41, 0x0a, 0x64, 0xb7, 0x5b, 0xed,
	0xfd, 0x6e, 0x29, 0x85, 0x00, 0x16, 0xf6, 0xf6, 0xbb, 0xe4, 0x59, 0x42, 0x2a, 0xe4, 0x5a, 0xcd,
	0xfd, 0xae, 0xbe, 0xbe, 0x53, 0x92, 0xd1, 0x0d, 0xb8, 0x5e, 0xdf, 0x6b, 0x75, 0x9b, 0x9f, 0x77,
	0x0f, 0x1a, 0xcd, 0x76, 0xb3, 0xd5, 0x68, 0xb6, 0xba, 0xa5, 0xb4, 0x56, 0x87, 0x6b, 0x51, 0xb2,
	0x37, 0x61, 0x61, 0xe4, 0xe0, 0x23, 0xeb, 0xd4, 0xcf, 0x11, 0x7f, 0x84, 0xca, 0x90, 0xb3, 0xdc,
	0xdd, 0xf1, 0xc0, 0xb3, 0x28, 0x8f, 0xbc, 0x1e, 0x0c, 0xb5, 0xbf, 0x24, 0x50, 0x77, 0x2c, 0xfb,
	0x58, 0xc7, 0xcf, 0xc7, 0xd8, 0xf5, 0xd0, 0x4a, 0x70, 0x0f, 0x49, 0x13, 0x2a, 0x95, 0x33, 0xf4,
	0x2f, 0x20, 0xfa, 0x1c, 0xdc, 0x3f, 0x3f, 0x4a, 0xa0, 0x72, 0xd3, 0xe8, 0x01, 0xe4, 0x07, 0x96,
	0x7d, 0x1c, 0xe6, 0x6c, 0xb1, 0x76, 0x23, 0x06, 0x47, 0x65, 0x09, 0xcd, 0xd0, 0x7d, 0x48, 0x5b,
	0xe6, 0x83, 0x24, 0x9d, 0x1e, 0xb1, 0x63, 0xe6, 0x35, 0xbf, 0x5b, 0xb9, 0xc8, 0xbc, 0xa6, 0xfd,
	0x21, 0xb1, 0x1e, 0x6f, 0x7f, 0x64, 0xd2, 0x36, 0x8c, 0x85, 0xb9, 0x26, 0x52, 0xbe, 0x1b, 0xdb,
	0x62, 0xc1, 0x7c, 0x12, 0xf1, 0x53, 0x91, 0xf7, 0xc5, 0xdd, 0xc7, 0xcc, 0x16, 0x2c, 0x63, 0x1a,
	0x9e, 0xe1, 0x4b, 0x50, 0x16, 0xdc, 0xfc, 0x05, 0x1a, 0x86, 0x67, 0xe8, 0xd4, 0x8a, 0x32, 0x22,
	0x4c, 0xe7, 0x60, 0x14, 0x33, 0xbf, 0x12, 0x46, 0x49, 0xfa, 0x70, 0x39, 0x49, 0x1f, 0xfe, 0x9b,
	0x04, 0x25, 0xee, 0xe3, 0x82, 0xad, 0xbf, 0x2a, 0x12, 0xba, 0x33, 0xed, 0x53, 0x64, 0x2a, 0x1f,
	0xe7, 0x0a, 0xf9, 0xbc, 0x0d, 0x45, 0x07, 0x3f, 0x1f, 0x5b, 0x0e, 0x36, 0x37, 0x2d, 0x3c, 0x30,
	0xd9, 0x99, 0xab, 0xe8, 0x91, 0x59, 0xca, 0x84, 0xeb, 0xf9, 0x13, 0x30, 0x89, 0x5a, 0x5f, 0x09,
	0x93, 0x19, 0xb9, 0x96, 0x94, 0xc9, 0xef, 0x7e, 0xdd, 0xd4, 0x1d, 0x3c, 0x4f, 0xdd, 0x08, 0xe6,
	0x93, 0xb8, 0xb8, 0x22, 0x97, 0x0a, 0xe4, 0x09, 0x44, 0xeb, 0xbc, 0xa3, 0x0b, 0xc7, 0xc1, 0xbb,
	0x6e, 0x70, 0x14, 0xfb, 0xef, 0xe8, 0xa1, 0x11, 0x94, 0x4c, 0x3a, 0x51, 0xc9, 0x7c, 0x27, 0x41,
	0x51, 0xdc, 0x5d, 0x54, 0x87, 0xa2, 0x2d, 0xa8, 0x94, 0x44, 0xc8, 0x88, 0x8b, 0x10, 0xbd, 0x1c,
	0x89, 0xbe, 0x0c, 0x39, 0x72, 0x53, 0x75, 0x8d, 0x3e, 0x0d, 0x52, 0xd1, 0x83, 0xa1, 0xb6, 0xc6,
	0xae, 0xfa, 0x6d, 0xa1, 0xef, 0x4e, 0x5b, 0x66, 0xa2, 0x76, 0x9d, 0xd8, 0x69, 0xa4, 0x31, 0x12,
	0x23, 0x29, 0x82, 0x6c, 0x99, 0x7e, 0xd7, 0x2d, 0x5b, 0xe6, 0x2c, 0xed, 0xb4, 0x5f, 0x65, 0x50,
	0x39, 0x8d, 0x48, 0x07, 0x64, 0xae, 0x3b, 0x7d, 0xb6, 0xbc, 0xa4, 0xb3, 0x01, 0x99, 0x75, 0xe9,
	0x2c, 0xcb, 0x0f, 0x36, 0x40, 0xab, 0x90, 0x33, 0x9f, 0x7c, 0x69, 0x90, 0x79, 0xd6, 0x1d, 0xbc,
	0x35, 0x4d, 0xfa, 0x6a, 0x83, 0xd9, 0xb1, 0xc6, 0x2e, 0xf0, 0x22, 0x00, 0xae, 0x0f, 0x90, 0xb9,
	0x00, 0xa0, 0x23, 0x00, 0xf8, 0x5e, 0x95, 0x15, 0x28, 0xf0, 0xc8, 0x73, 0xb5, 0x84, 0x2b, 0x50,
	0xe8, 0xcc, 0xe1, 0xcb, 0x77, 0x83, 0x77, 0x37, 0x21, 0x1f, 0x5c, 0x5e, 0xe4, 0xda, 0xee, 0x6c,
	0xef, 0xb6, 0x77, 0x9a, 0xa5, 0x14, 0x2a, 0x02, 0x7c, 0xd6, 0x5c, 0x7f, 0x72, 0xb0, 0xb9, 0xad,
	0x77, 0xc8, 0x35, 0x7e, 0x0d, 0x54, 0x3a, 0xee, 0x34, 0xeb, 0x7b, 0xad, 0x46, 0x49, 0x46, 0x8b,
	0xa0, 0xd0, 0x89, 0x8d, 0xbd, 0xee, 0xa3, 0x52, 0xba, 0xf6, 0x67, 0x16, 0x54, 0x5a, 0xf4, 0x8c,
	0x31, 0x6a, 0x83, 0xca, 0x8a, 0x86, 0x4c, 0xba, 0xe8, 0xf6, 0xec, 0x92, 0xaa, 0xbc, 0x7e, 0xc1,
	0x57, 0xa2, 0x96, 0x22, 0x88, 0xec, 0xb0, 0x9f, 0x86, 0x28, 0x5c, 0x05, 0x49, 0x10, 0x5b, 0xa0,
	0x36, 0xf0, 0x00, 0x07, 0x88, 0xb7, 0x66, 0x24, 0xa8, 0x9b, 0x2c, 0xc2, 0xc5, 0x2d, 0xec, 0x51,
	0x30, 0xd6, 0x19, 0xbe, 0x36, 0xf3, 0x4c, 0xac, 0xdc, 0x9e, 0xfd, 0x53, 0x25, 0x44, 0xa4, 0x7d,
	0xec, 0x24, 0xc4, 0xe8, 0x7d, 0x11, 0x41, 0x8c, 0xfd, 0xd9, 0xd2, 0x52, 0x48, 0x87, 0xc5, 0x8e,
	0x80, 0x78, 0x7b, 0xf6, 0x95, 0x1a, 0xe1, 0x1d, 0xff, 0x8b, 0xa1, 0xa5, 0xd0, 0x63, 0xc8, 0xb5,
	0x9d, 0x61, 0x0f, 0xbb, 0x57, 0xa0, 0x61, 0x1d, 0x32, 0x24, 0x1f, 0x51, 0x79, 0x5a, 0xbb, 0x96,
	0x04, 0x64, 0x0b, 0x8a, 0x5b, 0x58, 0x68, 0x27, 0xc5, 0x6f, 0x44, 0xfa, 0x6b, 0x31, 0x02, 0x14,
	0xff, 0x26, 0xd2, 0x52, 0x1b, 0x99, 0xa7, 0xf2, 0xe8, 0xf0, 0x70, 0x81, 0xfe, 0xa0, 0x7c, 0xf7,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0x20, 0x57, 0x15, 0xb6, 0x14, 0x00, 0x00,
}
